// ============================================================================
// AI STABILITY / HIGHER-ED DYNAMICS — the causal map
// Every node carries its counterpart from the 2009 PA Consulting
// "Afghanistan Stability / COIN Dynamics" diagram.
// Layout space: 2000 x 1150, hand-authored to echo the original's geography.
// ============================================================================

export const categories = [
  { id: 'pop',  label: 'Campus Community',            coin: 'Population / Popular Support',        color: '#4fc06a', ink: '#157a3d' },
  { id: 'aca',  label: 'Teaching, Research & Services', coin: 'Infrastructure, Economy & Services', color: '#a5d94f', ink: '#5c9c14' },
  { id: 'gov',  label: 'University Governance',        coin: 'Government',                          color: '#54b0ff', ink: '#1c7ac2' },
  { id: 'dist', label: 'Distributed / College IT',     coin: 'Tribal Governance',                   color: '#8fd0f5', ink: '#3b93cf' },
  { id: 'cit',  label: 'Central IT',                   coin: 'Afghanistan Security Forces',         color: '#7e97f7', ink: '#1d3a8f' },
  { id: 'shd',  label: 'Shadow AI',                    coin: 'Insurgents',                          color: '#ff6b5e', ink: '#c22525' },
  { id: 'ven',  label: 'Vendor Gold Rush',             coin: 'Crime & Narcotics',                   color: '#ffab4a', ink: '#d97a10' },
  { id: 'init', label: 'Institutional AI Initiatives', coin: 'Coalition Forces & Actions',          color: '#d8d2c4', ink: '#33302a' },
  { id: 'env',  label: 'Technology Substrate',         coin: 'Physical Environment',                color: '#c9a06a', ink: '#7a5b2f' },
];

// Region captions rendered faintly behind the graph, like the original's
// big section labels ("ANSF TACTICAL", "POPULATION CONDITIONS & BELIEFS"...)
export const regions = [
  { label: 'CENTRAL IT — OPERATIONS',        x: 700,  y: 78,   cat: 'cit',  size: 34 },
  { label: 'CENTRAL IT — INSTITUTIONAL',     x: 700,  y: 462,  cat: 'cit',  size: 30 },
  { label: 'INSTITUTIONAL AI INITIATIVES',   x: 250,  y: 625,  cat: 'init', size: 34, width: 340 },
  { label: 'UNIVERSITY GOVERNANCE',          x: 665,  y: 692,  cat: 'gov',  size: 32 },
  { label: 'DISTRIBUTED IT — LOCAL GOVERNANCE', x: 770, y: 998, cat: 'dist', size: 28 },
  { label: 'CAMPUS CONDITIONS & BELIEFS',    x: 1150, y: 625,  cat: 'pop',  size: 34 },
  { label: 'THE ADOPTION SPECTRUM',          x: 1630, y: 762,  cat: 'pop',  size: 26 },
  { label: 'SHADOW AI',                      x: 1390, y: 288,  cat: 'shd',  size: 44 },
  { label: 'VENDOR GOLD RUSH',               x: 1822, y: 522,  cat: 'ven',  size: 28 },
  { label: 'TEACHING, RESEARCH & SERVICES',  x: 1660, y: 1075, cat: 'aca',  size: 30 },
];

// Node tuple: [id, cat, x, y, label, coinCounterpart, description, flags]
// flags: b = rendered as a box (the adoption spectrum spine)
const N = [

  // ── TECHNOLOGY SUBSTRATE (the terrain nobody controls) ────────────────────
  ['env-model-pace', 'env', 1930, 160, 'Pace of Model Capability Change',
    'Terrain Harshness & Breadth',
    'Frontier models improve on a cadence measured in months. Every institutional process downstream of this node is measured in semesters or fiscal years. This mismatch is the terrain of the whole map.'],
  ['env-consumer-ubiquity', 'env', 1060, 118, 'Consumer AI Ubiquity',
    'Physical Environment',
    'ChatGPT is in every pocket before it is in any policy. The most capable tools arrive through the app store, not the enterprise catalog.'],
  ['env-compute-costs', 'env', 1930, 268, 'Compute & Licensing Cost Volatility',
    'Physical Environment',
    'Pricing models change quarterly. Budget cycles are annual. Nobody can forecast the cost of a commitment they are being asked to sign today.'],
  ['env-disruption-duration', 'env', 1952, 770, 'Duration of the Disruption',
    'Duration of Operation',
    'This is not a wave to ride out; it is a permanent change in the water level. Strategies built on "until this settles down" have no exit condition.'],
  ['env-capability-overhang', 'env', 1300, 60, 'Capability Overhang vs. Institutional Absorption',
    'Insurgent Terrain Advantage',
    'What the tools can already do exceeds what the institution has absorbed by years. Whoever moves informally captures the overhang first.'],

  // ── INSTITUTIONAL AI INITIATIVES (the coalition) ───────────────────────────
  ['init-leadership-attention', 'init', 150, 360, 'Leadership Attention Span',
    'Duration of Operation',
    'AI is this year’s strategic priority — competing with last year’s strategic priority and next year’s. Attention is the scarcest resource on the left side of this map.'],
  ['init-turnover', 'init', 330, 340, 'Leadership Turnover & Initiative Churn',
    'Coalition Adjustment of Approach',
    'Every new provost or CIO restarts the AI strategy clock. Institutional memory of what was tried lives in the people who left.'],
  ['init-strategy-unity', 'init', 170, 470, 'AI Strategy Coherence & Unity of Message',
    'Coalition "COIN" Support Strategy & Unity',
    'Five task forces, three centers, two strategic plans — one university. Coherence of message determines whether anyone downstream can act on it.'],
  ['init-taskforce', 'init', 340, 452, 'AI Task Force Formation & Output',
    'Coalition Development Operations',
    'The default institutional response to a fast-moving problem: convene a deliberative body. Output arrives as recommendations, on a timescale the problem does not respect.'],
  ['init-board-support', 'init', 130, 580, 'Board / Legislature Support',
    'Coalition Domestic Support',
    'Trustees and legislators read the same headlines the campus does. Their support funds the effort; their alarm redirects it.'],
  ['init-public-perception', 'init', 300, 560, 'Public & Media Perception of Campus AI',
    'US Domestic Perceived Cost/Benefit & Support',
    'One cheating scandal or one data breach shapes external perception more than a hundred quiet successes.'],
  ['init-budget', 'init', 150, 690, 'Central AI Budget Commitment',
    'US Gov’t Support for Operation',
    'Real money, committed across fiscal years, is the difference between a strategy and a press release.'],
  ['init-consultants', 'init', 330, 670, 'Consultant & Framework Engagements',
    'Coalition Advisory & Aid',
    'External experts arrive with maturity models and leave with retainers. Sometimes they transfer capability; sometimes they substitute for it.'],
  ['init-local-knowledge', 'init', 170, 800, 'Leadership Understanding of Unit Cultures',
    'Coalition Knowledge & Understanding of Social Structures',
    'The single most underrated variable on this map. Central strategy written without understanding how departments actually work gets the same reception as any occupying force’s plan.'],
  ['init-mandate-balance', 'init', 350, 780, 'Balance of Mandate vs. Enablement',
    'Coalition Appropriate Balance of Effort & Force',
    'Too much mandate breeds resistance and workarounds; too much laissez-faire breeds chaos. Almost nobody gets this dial right on the first try.'],
  ['init-execution', 'init', 250, 892, 'Central Initiative Execution Capacity',
    'Coalition Execution Capacity & Priorities',
    'Strategy documents do not deploy themselves. Execution capacity — people who can actually ship — is chronically oversubscribed.'],
  ['init-peer-pressure', 'init', 120, 900, 'Peer-Institution Comparison Pressure',
    'Breadth of Coalition & Support',
    'Every peer announcement ("University X partners with...") resets the baseline for what leadership feels compelled to match.'],
  ['init-pilots', 'init', 380, 940, 'Flagship Pilots & Announcements',
    'Coalition Development Operations — Infrastructure & Services',
    'Visible, fundable, announceable. Whether pilots convert into durable services is a different node entirely.'],

  // ── CENTRAL IT — OPERATIONS (the security forces, tactical) ────────────────
  ['cit-helpdesk', 'cit', 520, 140, 'Service Desk AI Question Load',
    'Total Security Force Capacity & Focus',
    'Every new tool — sanctioned or not — lands here eventually. The queue is the truest sensor of what campus is actually doing with AI.'],
  ['cit-security-ops', 'cit', 700, 132, 'Security Operations & Monitoring',
    'ISR / Open Source Ops',
    'Watching the network for what talks to what. Sees traffic, not intent; volume, not context.'],
  ['cit-vetting', 'cit', 880, 150, 'Tool Vetting & Review Throughput',
    'ANSF Capacity, Priorities & Effectiveness',
    'The chokepoint of the whole sanctioned path. Every review done carefully is a month a requester spends deciding whether to wait or route around.'],
  ['cit-iam', 'cit', 500, 240, 'Identity & Access Integration',
    'ANSF Training & Mentoring',
    'Single sign-on is the difference between a tool the institution can see and govern, and a tool it merely coexists with.'],
  ['cit-blocking', 'cit', 670, 230, 'Blocking & Restriction Actions',
    'Sweep Ops (Clear)',
    'Blocking a domain is fast, visible, and satisfying. It also teaches ten thousand smart people to use their phones instead. Clearing is not holding.'],
  ['cit-catalog', 'cit', 862, 250, 'Sanctioned AI Tool Catalog Quality',
    'Policing & Security Ops (Hold)',
    'The "hold" mission: a sanctioned alternative good enough that people choose it voluntarily. The catalog competes with the entire consumer AI market, every day.'],
  ['cit-incident', 'cit', 540, 330, 'Incident Response Load',
    'ANSF & Coalition Damages / Casualties',
    'Every shadow-tool data exposure becomes central IT’s incident to clean up, regardless of who signed up for the tool.'],
  ['cit-visibility', 'cit', 720, 330, 'Visibility into Unit AI Use',
    'Coalition Visibility to Population',
    'EDUCAUSE keeps finding the same thing: there are far more AI tools on campus than IT knows about. You cannot govern what you cannot see, and you cannot see what people are afraid to show you.'],
  ['cit-detections', 'cit', 900, 340, 'Shadow AI Discoveries',
    'Insurgent Damages & Casualties',
    'Each discovery is simultaneously a security win and a trust event — depending entirely on what happens to the person who gets discovered.'],
  ['cit-comms', 'cit', 1000, 210, 'IT Communications Quality & Reach',
    'IO / Strategic Communication',
    'The institution’s official story about AI, competing for attention against the department grapevine and a thousand LinkedIn hot takes.'],

  // ── CENTRAL IT — INSTITUTIONAL (the security forces, capacity) ─────────────
  ['citi-leadership', 'cit', 540, 410, 'IT Unit Leadership & Tactical Capacity',
    'ANSF Unit Leadership & Tactical Capacity',
    'Middle leadership translates strategy into service. When it is strong, everything below runs; when hollow, nothing above matters.'],
  ['citi-staffing', 'cit', 710, 400, 'IT Staff Recruiting & Retention',
    'ANSF Manpower, Recruiting & Retention',
    'The institution trains people in AI operations, and the market pays double for exactly those skills. Retention is a war fought with non-salary currency.'],
  ['citi-skills', 'cit', 880, 420, 'IT Staff AI Skill & Morale',
    'ANSF Avg. Professionalism, Skill, Discipline & Morale',
    'Skill decays against a moving frontier. Morale decays against a queue that never shrinks. Both are load-bearing.'],
  ['citi-training', 'cit', 520, 500, 'IT Staff Training & Development',
    'ANSF Training & Mentoring',
    'Sending staff to learn the tools of eighteen months from now, using the training budget of five years ago.'],
  ['citi-funding', 'cit', 690, 490, 'Central IT Funding Adequacy',
    'ANSF Funding Adequacy',
    'Every duplicated departmental license and surprise renewal drains the pool that was supposed to fund the platform everyone shares.'],
  ['citi-architecture', 'cit', 860, 510, 'Enterprise Architecture & Platform Capacity',
    'ANSF Institutional & Execution Capacity',
    'The unglamorous substrate — data pipelines, APIs, integration — that decides whether "we should use AI for that" takes a week or a year.'],
  ['citi-credibility', 'cit', 930, 580, 'Central IT Credibility with Units',
    'Coalition / Homeland Acceptance of Afghan Methods',
    'Earned in years of delivered services; spent in a single heavy-handed blocking decision or a review queue that swallows requests whole.'],
  ['citi-burnout', 'cit', 600, 570, 'IT Staff Burnout',
    'ANSF Morale (Attrition)',
    'The compounding interest on every other deficit in this cluster. Burnout converts funding problems into people problems, permanently.'],

  // ── UNIVERSITY GOVERNANCE (the government) ─────────────────────────────────
  ['gov-policy-capacity', 'gov', 520, 650, 'Policy Development Capacity',
    'Gov’t Policy Quality & Investment',
    'The number of people who can write defensible, usable technology policy is small everywhere. In most institutions it rounds to a committee with day jobs.'],
  ['gov-aup', 'gov', 700, 640, 'AI Acceptable-Use Policy Quality & Execution',
    'R.O.L. Policy, Execution & Perceived Fairness',
    'As of 2025, only about 39% of institutions have one at all. A policy nobody can find, read, or apply is indistinguishable from no policy — except that it can still be enforced selectively.'],
  ['gov-policy-lag', 'gov', 862, 660, 'Policy Lag Behind Tech Pace',
    'Significant Delay (systemic)',
    'The signature delay of the whole map. By the time a policy clears review, the tools it describes have been superseded twice. The lag is structural, not a failure of effort.'],
  ['gov-committee-speed', 'gov', 500, 740, 'Committee & Senate Process Speed',
    'Gov’t Reach, Execution Capacity & Investment',
    'Shared governance is a feature, not a bug — but it prices every decision in months. The insurgency’s decision cycle is a browser refresh.'],
  ['gov-transparency', 'gov', 670, 730, 'Transparency of Decisions & Investments',
    'Transparency of Gov’t Processes & Investments',
    'When people can see why a tool was approved or denied, they extend trust. When decisions emerge from a black box, they route around it.'],
  ['gov-enforcement', 'gov', 840, 750, 'Consistency of Enforcement',
    'R.O.L. Execution & Perceived Fairness',
    'A rule enforced on some people some of the time is experienced as arbitrary power, not policy. Inconsistency manufactures sympathy for the shadow path.'],
  ['gov-integrity-policy', 'gov', 530, 830, 'Academic Integrity Policy Modernization',
    'R.O.L. Policy & Execution',
    'Integrity frameworks written for plagiarism are being asked to adjudicate a technology that writes. Every ambiguity lands on an individual instructor’s desk.'],
  ['gov-integration', 'gov', 700, 820, 'Integration of Local Unit Structures',
    'Gov’t Integration of Local Tribal Structures',
    'The original diagram’s quiet insight: central authority that incorporates local structures gains reach; central authority that ignores them gains enemies.'],
  ['gov-data-gov', 'gov', 862, 840, 'Data Governance & Classification Maturity',
    'Gov’t Workforce Skill & Availability',
    'If nobody can say which data is safe to put in which tool, every user makes that call alone, at 11pm, with a deadline.'],
  ['gov-funding-model', 'gov', 590, 885, 'IT Funding Model (Central vs. Unit)',
    'Tax Revenues',
    'Whoever holds the budget holds the strategy. A funding model that rewards units for buying their own tools will produce exactly that.'],

  // ── DISTRIBUTED / COLLEGE IT (tribal governance) ───────────────────────────
  ['dist-college-it', 'dist', 600, 950, 'College & Unit IT Capacity',
    'Structures & Beliefs (Tribal)',
    'Closest to the actual work, trusted by their faculty, chronically under-resourced. Distributed IT is where central strategy meets local reality — and where it usually gets renegotiated.'],
  ['dist-local-norms', 'dist', 770, 940, 'Local Unit Norms & Practices',
    'Tribal Structures & Beliefs',
    'Engineering, Fine Arts, and the Law School are effectively different countries with different AI cultures. Policy that pretends otherwise gets local-law treatment.'],
  ['dist-guidelines', 'dist', 930, 950, 'Unit-Level AI Guideline Patchwork',
    'Local Governance Structures',
    'Each college writes its own guidance in the vacuum central policy leaves. The result is sincere, thoughtful, and mutually contradictory.'],
  ['dist-trust', 'dist', 620, 1040, 'College IT ↔ Central IT Relationship',
    'Central Gov’t ↔ Tribal Relations',
    'The most valuable edge on this map. Where the relationship is strong, distributed IT is central IT’s sensor network. Where it is weak, they are rival service providers.'],
  ['dist-procurement', 'dist', 790, 1030, 'Local Procurement Autonomy',
    'Local Economic Activity',
    'A p-card and a plausible justification is a procurement process. Autonomy that outruns visibility is how the institution ends up owning forty AI tools it has never heard of.'],
  ['dist-rivalry', 'dist', 950, 1040, 'Unit Rivalry & Resource Competition',
    'Ethnic / Tribal Rivalry',
    'Colleges compete for students, faculty, and indirect-cost returns. An AI advantage is a competitive advantage, and sharing it is not the instinct.'],
  ['dist-innovation', 'dist', 700, 1105, 'Local Innovation & Skunkworks',
    'Local Development',
    'The best AI work on campus is often happening in a lab or a dean’s office pilot nobody upstairs knows about. It is simultaneously the future of the institution and a compliance question.'],
  ['dist-duplication', 'dist', 860, 1110, 'Duplication of Effort Across Units',
    'Fragmentation of Local Efforts',
    'Nine units independently evaluating the same tool, negotiating the same contract, and making the same mistakes — in parallel, invisibly.'],

  // ── CAMPUS CONDITIONS & BELIEFS (the population) ───────────────────────────
  ['pop-expectations', 'pop', 1000, 500, 'Expectations Set by Consumer AI',
    'Expectations for Security, Services & Employment',
    'People’s baseline is set by the best tool they used last night, free, on their phone. Enterprise offerings are judged against that bar, not against last year’s enterprise offerings.'],
  ['pop-msg-relative', 'pop', 1160, 480, 'Relative Message Credibility: Institution vs. Grapevine',
    'Relative Message Quality — Gov’t vs. Insurgents',
    'The official channel says "use the sanctioned tool." The hallway says "here’s what actually works." Whichever message is more useful wins, and usefulness is not the official channel’s strength.'],
  ['pop-perceived-usefulness', 'pop', 1310, 500, 'Perceived Usefulness of Sanctioned Tools',
    'Perception of Gov’t Strength & Intent',
    'The load-bearing node of the entire right half of the map. If the sanctioned path is genuinely useful, most of this diagram calms down. If it is not, no policy can compensate.'],
  ['pop-trust-central', 'pop', 990, 590, 'Trust in Central IT & Administration',
    'Popular Support / Tolerance of Gov’t',
    'Accumulates slowly through delivered value; evaporates instantly through surveillance vibes or punitive enforcement. The whole map is, in the end, a machine for producing or destroying this.'],
  ['pop-fairness', 'pop', 1140, 580, 'Perceived Fairness of AI Policy',
    'Perceived Damages / Use of Force by Gov’t & Coalition',
    'Faculty punished for what administrators demo on stage; students disciplined for what the syllabus never defined. Perceived unfairness recruits for the shadow path better than any tool ever could.'],
  ['pop-integrity-anxiety', 'pop', 980, 680, 'Academic-Integrity Anxiety',
    'Fear of Insurgent Attack / Repercussions',
    'Instructors fear undetectable cheating; students fear false accusation by unreliable detectors. Both fears are rational, and both corrode the classroom trust the institution runs on.'],
  ['pop-replacement-anxiety', 'pop', 1130, 670, 'Job & Craft Displacement Anxiety',
    'Cultural Erosion / Displacement',
    'Staff hear "efficiency" and reasonably wonder whose position it means. Faculty wonder what teaching means when the essay writes itself. This anxiety is the quiet engine behind much resistance labeled as principle.'],
  ['pop-ai-literacy', 'pop', 1280, 680, 'Faculty & Staff AI Literacy',
    'Population Skill & Availability',
    'Not prompt tricks — judgment: knowing what these tools are, where they fail, and what data they must never see. The cheapest lever on the map, and the most chronically underfunded.'],
  ['pop-student-fluency', 'pop', 1000, 770, 'Student AI Fluency (Outpacing Faculty)',
    'Population Youth Dynamics',
    'Students adopted these tools in a semester. The generational fluency inversion — students ahead of instructors — destabilizes classroom authority in ways syllabus language cannot fix.'],
  ['pop-workload', 'pop', 1150, 760, 'Faculty & Staff Workload / Time Scarcity',
    'Population Basic Needs',
    'Nobody has time to learn the sanctioned way to do anything. Time scarcity is the silent ally of whichever path has the fewest clicks.'],
  ['pop-peer-norms', 'pop', 1300, 770, 'Peer Norms & Department Culture',
    'Average Connectedness of Population',
    'People do what the respected person down the hall does. Adoption spreads through departments along friendship graphs, not org charts.'],
  ['pop-visible-wins', 'pop', 1030, 860, 'Visible Wins from Sanctioned AI',
    'Visible Gains in Security, Services & Employment',
    'One colleague publicly saving ten hours a week with an approved tool converts more people than any all-campus email. Wins must be visible to work.'],
  ['pop-satisfaction', 'pop', 1180, 850, 'Satisfaction with Institutional AI Support',
    'Satisfaction with Gains in Security, Services & Employment',
    'The rolling referendum on whether the institution is helping or in the way. Feeds directly into which box of the spectrum people stand in.'],
  ['pop-disclosure', 'pop', 1330, 860, 'Willingness to Disclose AI Use',
    'Population Willingness to Share Information',
    'The institution’s entire visibility problem in one variable. People disclose when disclosure is safe and useful; they hide when it is career-risky. Punish honesty once and watch this node collapse.'],
  ['pop-perceived-risk', 'pop', 1080, 930, 'Perceived Personal Risk of AI Use',
    'Perceived Security',
    'Am I allowed? Will this be held against me? Ambiguity reads as risk, and risk pushes use underground where nobody can help.'],

  // ── THE ADOPTION SPECTRUM (the five boxes) ─────────────────────────────────
  ['spine-champion', 'pop', 1370, 700, 'Champions on the Sanctioned Path',
    'Population Actively Supporting Gov’t & Security Forces',
    'Using approved tools, sharing what works, showing up to office hours. The institution’s force multiplier — and the first people lost when the sanctioned path disappoints.', 'b'],
  ['spine-sympathetic', 'pop', 1500, 700, 'Sympathetic but Underserved',
    'Population Sympathizing with Gov’t',
    'Would happily use institutional tools if they were good enough and easy to find. The recoverable middle. Most of campus lives here or next door.', 'b'],
  ['spine-fence', 'pop', 1630, 700, 'On the Fence',
    'Neutral / On the Fence',
    'Waiting to see whether disclosure is rewarded or punished, whether the tools are real, whether this is a priority or a fad. Every policy decision moves this box one direction or the other.', 'b'],
  ['spine-shadow', 'pop', 1760, 700, 'Quietly on the Shadow Path',
    'Population Sympathizing with Insurgents',
    'Using personal accounts for work, not out of malice but because it works. Say the quiet part: this is most of your early adopters. They are one good sanctioned tool away from coming back.', 'b'],
  ['spine-outside', 'pop', 1890, 700, 'Fully Outside the Institutional Path',
    'Population Actively Supporting Insurgency',
    'Whole workflows, budgets, and team practices built on unsanctioned tools. Re-onboarding them costs more each month; some are never coming back.', 'b'],

  // ── SHADOW AI (the insurgency) ─────────────────────────────────────────────
  ['shd-consumer-ecosystem', 'shd', 1200, 140, 'Consumer AI Ecosystem Enablement',
    'Outside Support / Enablement of Insurgents',
    'The shadow path is armed and funded by the most capitalized industry on earth. Free tiers, viral features, one-click signup — external support the institution cannot interdict.'],
  ['shd-tool-appeal', 'shd', 1380, 130, 'Shadow Tool Capability & Appeal',
    'Insurgent Leadership, Training, Skill & Experience',
    'The uncomfortable core fact: the unsanctioned tools are often simply better. This is an insurgency with superior equipment.'],
  ['shd-agility', 'shd', 1550, 150, 'Shadow Adopter Agility Advantage',
    'Insurgent Terrain Advantage',
    'No procurement, no review, no committee. The shadow path’s decision loop is minutes; the institution’s is months. On terrain that changes monthly, agility compounds.'],
  ['shd-havens', 'shd', 1160, 230, 'Unmonitored Environments',
    'Havens / Ability to Operate',
    'Personal devices, personal accounts, browser extensions, home networks. Every blocking action expands the haven by pushing activity somewhere with even less visibility.'],
  ['shd-adoption', 'shd', 1340, 230, 'Shadow AI Adoption',
    'Insurgent Capacity, Priorities & Effectiveness',
    'The center of the insurgency cluster. Surveys put unsanctioned AI use around 56% of higher-ed workers — a majority of the institution’s own people, routing around it to do its work.'],
  ['shd-word-of-mouth', 'shd', 1520, 240, 'Word-of-Mouth Recruiting',
    'Insurgent Recruiting, Retention, Manpower & ISR',
    '"Just use this, it’s way better" — whispered in every hallway, Slack, and group chat. The shadow path’s marketing budget is zero and its conversion rate is spectacular.'],
  ['shd-personal-accounts', 'shd', 1140, 330, 'Personal-Account LLM Use',
    'Insurgent Small Units',
    'Institutional work flowing through consumer accounts: no contract, no data protection, no audit trail, no recourse. The most common single behavior on this map.'],
  ['shd-dept-saas', 'shd', 1310, 330, 'Department Credit-Card SaaS',
    'Organized Insurgent Factions',
    'A team, a p-card, and a subscription: shadow AI at the organizational level, often with real budgets and real institutional data, entirely off the books.'],
  ['shd-coordination', 'shd', 1480, 340, 'Coordination via Group Chats & Forums',
    'Coordination Among Insurgent Factions',
    'Discord servers, subreddits, department Slacks where the real documentation lives. Better knowledge-sharing than the sanctioned path has ever achieved.'],
  ['shd-workarounds', 'shd', 1630, 330, 'Shadow Solutions Filling Service Gaps',
    'Insurgent Provision of Gov’t & Services',
    'The insurgency governs where the institution doesn’t: when the shadow tool is how the office actually functions, it has become critical infrastructure without ever being approved.'],
  ['shd-fear-crackdown', 'shd', 1200, 430, 'Fear of Crackdown vs. Amnesty Perception',
    'Fear of Gov’t / ANSF / Coalition Repercussions',
    'If coming clean means punishment, nobody comes clean. Amnesty — a safe path back — is the cheapest visibility program ever devised, and almost no institution offers one.'],
  ['shd-strategic-comms', 'shd', 1370, 430, 'Grapevine Narratives About IT & Policy',
    'Insurgent Strategic Communication & Affiliation with Population',
    '"Central IT just blocks everything." "The policy is a trap." Fair or not, the shadow path’s narrative spreads faster than the institution’s and is stickier.'],
  ['shd-data-leakage', 'shd', 1540, 440, 'Sensitive Data Exposure Events',
    'Insurgent Targeted Attacks',
    'Student records in consumer chatbots, grant data in free tiers. Each event is ammunition for the crackdown faction — which triggers the controls that drive more use underground.'],

  // ── VENDOR GOLD RUSH (crime & narcotics) ───────────────────────────────────
  ['ven-pitches', 'ven', 1740, 400, 'EdTech AI Vendor Pitch Volume',
    'Narcotics & Criminal Activity Levels',
    'Every inbox on campus, every week. The gold rush’s prospectors, selling shovels to every stratum of the org chart simultaneously.'],
  ['ven-ai-washing', 'ven', 1900, 390, 'AI-Washing of Existing Products',
    'Criminal / Trafficking Capability',
    'Last year’s product, this year’s "AI-powered" sticker, next year’s price. Washing muddies vetting for everyone, because now everything requires review.'],
  ['ven-free-pilots', 'ven', 1730, 480, '"Free Pilot" Seeding',
    'Funding & Material Support to Insurgents',
    'The narcotics economics of the map: free product seeds dependence, dependence becomes workflow, workflow becomes a renewal invoice addressed to someone who never agreed to buy anything.'],
  ['ven-fomo', 'ven', 1890, 470, 'FOMO-Driven Purchasing',
    'Illicit Funding Flows',
    'Bought because a peer institution announced it, a dean saw a demo, or a trustee asked "what’s our AI strategy?" Fear of missing out is the sector’s most reliable purchasing trigger.'],
  ['ven-procurement-bypass', 'ven', 1740, 560, 'Procurement Bypass',
    'Likelihood of Crime / Insurgent Support for Payment',
    'When the official pipeline takes nine months, the p-card takes nine minutes. Bypass is not deviance; it is arbitrage on institutional latency.'],
  ['ven-contract-backlog', 'ven', 1900, 550, 'Contract, DPA & Security Review Backlog',
    'Criminal Justice System Capacity',
    'The queue where purchases wait for privacy and security review. Every month of queue time is a month of incentive to skip the queue entirely.'],
  ['ven-license-duplication', 'ven', 1770, 645, 'Duplicated Licenses & Spend',
    'Illicit Agricultural Production, Trade & Employment',
    'The same tool bought nine times at unit prices instead of once at scale. The invisible tax fragmentation levies on the whole institution.'],
  ['ven-lock-in', 'ven', 1915, 635, 'Vendor Lock-In & Data Portability Risk',
    'Criminal Coercion',
    'Once your courses, data, and workflows live in the tool, the renewal negotiation is not a negotiation. Lock-in is the gold rush’s long game.'],
  ['ven-renewal-squeeze', 'ven', 1690, 610, 'Renewal Price Squeeze',
    'Extortion Economics',
    'Year one is free, year two is cheap, year three is whatever the vendor decides your dependence is worth.'],

  // ── TEACHING, RESEARCH & SERVICES (infrastructure & economy) ───────────────
  ['aca-sanctioned-convenience', 'aca', 1420, 830, 'Relative Convenience: Sanctioned vs. Shadow Path',
    'Legit vs. Illicit Relative Economic Opportunity',
    'The decisive economic variable, borrowed straight from the original: people take the path that pays. If the legitimate path is slower, worse, and harder to find, choosing it is charity.'],
  ['aca-lms', 'aca', 1580, 820, 'LMS & Courseware AI Integration',
    'Infrastructure Development & Sustainment',
    'AI arriving inside the tools campus already uses — often switched on by the vendor before anyone decided anything. Infrastructure that updates itself is also policy that writes itself.'],
  ['aca-curriculum', 'aca', 1740, 830, 'AI in Curriculum & Graduate Skills',
    'Population Basic Needs Service Levels',
    'What students actually need from the institution now. Programs that integrate AI honestly are providing the service; programs that ban it are ceding it to YouTube.'],
  ['aca-research-advantage', 'aca', 1900, 840, 'Research Competitiveness in the AI Era',
    'Economic Activity',
    'Labs with AI capability win grants, recruit better students, publish faster. The competitive gradient is steep and getting steeper, and it does not wait for policy.'],
  ['aca-assessment', 'aca', 1440, 920, 'Assessment & Pedagogy Redesign',
    'Reconstruction Efforts',
    'The slow, real work of redesigning courses for a world where the essay is no longer proof of thinking. Cannot be mandated, only supported — and it takes years.'],
  ['aca-course-policies', 'aca', 1600, 910, 'Course-by-Course AI Policy Patchwork',
    'Local Services (Fragmented)',
    'Allowed in one course, cheating in the next, undefined in the third — sometimes within one student’s Tuesday. The patchwork is each instructor’s rational answer to a vacuum.'],
  ['aca-student-services', 'aca', 1760, 920, 'AI in Student Services & Advising',
    'Civilian Services (SWET, Healthcare, Education)',
    'Advising chatbots, financial-aid triage, accessibility tools. Where AI helps students directly — and where a bad deployment does the most visible damage.'],
  ['aca-grants', 'aca', 1910, 930, 'AI Grant & Funding Capture',
    'Foreign Aid & Investment',
    'Federal agencies and foundations are pouring money into AI. Capturing it requires the very capacity — computing, data readiness, staff — the institution is struggling to build.'],
  ['aca-research-computing', 'aca', 1480, 1010, 'Research Computing & Data Capacity',
    'Power, Water & Infrastructure',
    'GPUs, storage, secure enclaves. The physical economy of institutional AI, perpetually oversubscribed and always one grant cycle behind demand.'],
  ['aca-data-readiness', 'aca', 1650, 1010, 'Institutional Data Readiness',
    'Legitimate Agricultural Production',
    'Clean, governed, well-described data is the legitimate crop of the AI economy. Most institutional data is none of those things, which caps everything anyone hopes to build on it.'],
  ['aca-teaching-quality', 'aca', 1820, 1010, 'Perceived Teaching & Learning Quality',
    'Quality of Life',
    'The outcome the whole map allegedly serves. Rises when AI is integrated deliberately; erodes when the classroom becomes a detection arms race.'],
];

// Edge notation: 'from>to' with optional '|d' for a significant-delay marker.
const E = [
  // Substrate → everything
  'env-model-pace>gov-policy-lag|d',
  'env-model-pace>shd-tool-appeal',
  'env-model-pace>citi-skills|d',
  'env-model-pace>citi-staffing|d',
  'env-model-pace>ven-ai-washing',
  'env-model-pace>env-capability-overhang',
  'env-model-pace>pop-replacement-anxiety',
  'env-consumer-ubiquity>pop-expectations',
  'env-consumer-ubiquity>shd-personal-accounts',
  'env-consumer-ubiquity>pop-student-fluency',
  'env-consumer-ubiquity>shd-consumer-ecosystem',
  'env-compute-costs>citi-funding',
  'env-compute-costs>aca-research-computing',
  'env-capability-overhang>shd-agility',
  'env-capability-overhang>pop-integrity-anxiety',
  'env-disruption-duration>init-leadership-attention',
  'env-disruption-duration>init-board-support|d',

  // Institutional initiatives (the coalition)
  'init-board-support>init-budget',
  'init-public-perception>init-board-support',
  'init-peer-pressure>init-taskforce',
  'init-peer-pressure>init-pilots',
  'init-leadership-attention>init-strategy-unity',
  'init-turnover>init-strategy-unity',
  'init-turnover>init-leadership-attention',
  'init-taskforce>init-strategy-unity|d',
  'init-taskforce>gov-policy-capacity',
  'init-taskforce>gov-aup|d',
  'init-consultants>init-taskforce',
  'init-consultants>init-budget',
  'init-strategy-unity>init-execution',
  'init-strategy-unity>pop-msg-relative',
  'init-budget>init-execution',
  'init-budget>citi-funding',
  'init-local-knowledge>init-mandate-balance',
  'init-local-knowledge>init-execution',
  'init-mandate-balance>pop-trust-central',
  'init-mandate-balance>dist-trust',
  'init-execution>cit-catalog',
  'init-execution>pop-visible-wins|d',
  'init-pilots>init-public-perception',
  'init-pilots>pop-expectations',
  'init-pilots>pop-replacement-anxiety',
  'init-pilots>ven-pitches',
  'pop-visible-wins>init-board-support',
  'shd-data-leakage>init-public-perception',
  'shd-data-leakage>init-taskforce',
  'aca-teaching-quality>init-public-perception',
  'aca-research-advantage>init-board-support',
  'ven-fomo>init-pilots',

  // Central IT — institutional capacity
  'citi-funding>citi-staffing',
  'citi-funding>citi-training',
  'citi-funding>citi-architecture',
  'citi-staffing>citi-skills',
  'citi-training>citi-skills|d',
  'citi-skills>cit-vetting',
  'citi-skills>cit-security-ops',
  'citi-skills>citi-leadership',
  'citi-leadership>cit-comms',
  'citi-leadership>citi-training',
  'citi-architecture>cit-iam',
  'citi-architecture>cit-catalog',
  'citi-architecture>aca-research-computing|d',
  'citi-burnout>citi-staffing',
  'citi-credibility>pop-trust-central',
  'citi-credibility>dist-trust',

  // Central IT — operations
  'cit-helpdesk>citi-burnout',
  'cit-incident>citi-burnout',
  'cit-incident>citi-credibility',
  'cit-incident>cit-blocking',
  'cit-vetting>cit-catalog',
  'cit-vetting>ven-contract-backlog',
  'cit-catalog>pop-perceived-usefulness',
  'cit-catalog>aca-sanctioned-convenience',
  'cit-catalog>citi-credibility',
  'cit-catalog>spine-sympathetic',
  'cit-iam>cit-visibility',
  'cit-security-ops>cit-detections',
  'cit-detections>cit-blocking',
  'cit-detections>shd-fear-crackdown',
  'cit-blocking>shd-havens',
  'cit-blocking>pop-trust-central',
  'cit-blocking>dist-trust',
  'cit-blocking>cit-vetting|d',
  'cit-visibility>cit-detections',
  'cit-visibility>init-local-knowledge',
  'cit-visibility>cit-catalog',
  'cit-comms>pop-msg-relative',
  'cit-comms>pop-ai-literacy',
  'pop-expectations>cit-helpdesk',
  'shd-adoption>cit-helpdesk',
  'shd-data-leakage>cit-incident',

  // Governance
  'gov-policy-capacity>gov-aup',
  'gov-policy-capacity>gov-integrity-policy',
  'gov-committee-speed>gov-policy-lag',
  'gov-policy-lag>gov-aup',
  'gov-aup>gov-enforcement',
  'gov-aup>pop-fairness',
  'gov-enforcement>pop-fairness',
  'gov-enforcement>shd-fear-crackdown',
  'gov-enforcement>spine-fence',
  'gov-transparency>pop-trust-central',
  'gov-transparency>pop-fairness',
  'gov-integrity-policy>pop-integrity-anxiety',
  'gov-integrity-policy>aca-assessment',
  'gov-integration>dist-guidelines',
  'gov-integration>dist-trust|d',
  'gov-data-gov>cit-vetting',
  'gov-data-gov>shd-data-leakage',
  'gov-data-gov>aca-data-readiness|d',
  'gov-funding-model>citi-funding',
  'gov-funding-model>dist-procurement',
  'gov-funding-model>dist-college-it',
  'gov-funding-model>dist-rivalry',
  'shd-adoption>gov-policy-lag|d',
  'pop-integrity-anxiety>gov-integrity-policy',
  'aca-course-policies>gov-enforcement',

  // Distributed IT
  'dist-college-it>dist-innovation',
  'dist-college-it>dist-guidelines',
  'dist-college-it>cit-visibility',
  'dist-local-norms>dist-guidelines',
  'dist-local-norms>pop-peer-norms',
  'dist-guidelines>aca-course-policies',
  'dist-guidelines>pop-fairness',
  'dist-trust>cit-visibility',
  'dist-trust>dist-duplication',
  'dist-procurement>ven-fomo',
  'dist-procurement>shd-dept-saas',
  'dist-rivalry>dist-duplication',
  'dist-rivalry>dist-trust',
  'dist-innovation>pop-visible-wins',
  'dist-innovation>shd-dept-saas',
  'dist-duplication>ven-license-duplication',

  // Campus community
  'pop-expectations>pop-perceived-usefulness',
  'pop-expectations>shd-adoption',
  'pop-perceived-usefulness>pop-satisfaction',
  'pop-perceived-usefulness>shd-adoption',
  'pop-perceived-usefulness>pop-visible-wins',
  'pop-perceived-usefulness>dist-procurement',
  'pop-ai-literacy>pop-perceived-usefulness',
  'pop-ai-literacy>pop-integrity-anxiety',
  'pop-ai-literacy>aca-curriculum',
  'pop-student-fluency>pop-integrity-anxiety',
  'pop-student-fluency>aca-assessment',
  'pop-student-fluency>pop-workload',
  'pop-workload>shd-adoption',
  'pop-workload>pop-ai-literacy',
  'pop-workload>aca-assessment',
  'pop-trust-central>pop-disclosure',
  'pop-trust-central>spine-sympathetic',
  'pop-fairness>pop-trust-central',
  'pop-fairness>pop-disclosure',
  'pop-fairness>shd-adoption',
  'pop-integrity-anxiety>pop-disclosure',
  'pop-integrity-anxiety>pop-perceived-risk',
  'pop-replacement-anxiety>spine-fence',
  'pop-replacement-anxiety>pop-trust-central',
  'pop-perceived-risk>shd-havens',
  'pop-perceived-risk>pop-disclosure',
  'pop-peer-norms>shd-word-of-mouth',
  'pop-peer-norms>pop-ai-literacy',
  'pop-msg-relative>pop-trust-central',
  'pop-visible-wins>pop-satisfaction',
  'pop-visible-wins>pop-trust-central|d',
  'pop-satisfaction>spine-champion',
  'pop-disclosure>cit-visibility',
  'spine-champion>pop-visible-wins',
  'spine-outside>shd-adoption',

  // The spectrum flows both ways, like the original's five boxes
  'spine-champion>spine-sympathetic',
  'spine-sympathetic>spine-champion',
  'spine-sympathetic>spine-fence',
  'spine-fence>spine-sympathetic',
  'spine-fence>spine-shadow',
  'spine-shadow>spine-fence',
  'spine-shadow>spine-outside',
  'spine-outside>spine-shadow',
  'shd-tool-appeal>spine-shadow',
  'shd-word-of-mouth>spine-shadow',
  'aca-sanctioned-convenience>spine-sympathetic',

  // Shadow AI
  'shd-consumer-ecosystem>shd-tool-appeal',
  'shd-consumer-ecosystem>shd-havens',
  'shd-consumer-ecosystem>shd-personal-accounts',
  'shd-tool-appeal>shd-adoption',
  'shd-tool-appeal>pop-expectations',
  'shd-havens>shd-adoption',
  'shd-word-of-mouth>shd-adoption',
  'shd-adoption>shd-coordination',
  'shd-adoption>shd-workarounds',
  'shd-adoption>shd-data-leakage',
  'shd-personal-accounts>shd-data-leakage',
  'shd-dept-saas>shd-data-leakage',
  'shd-dept-saas>ven-license-duplication',
  'shd-workarounds>aca-sanctioned-convenience',
  'shd-workarounds>shd-word-of-mouth',
  'shd-coordination>shd-word-of-mouth',
  'shd-coordination>shd-agility',
  'shd-agility>shd-adoption',
  'shd-fear-crackdown>shd-havens',
  'shd-fear-crackdown>pop-disclosure',
  'shd-strategic-comms>pop-msg-relative',
  'shd-strategic-comms>shd-word-of-mouth',
  'shd-data-leakage>shd-fear-crackdown',
  'ven-free-pilots>shd-dept-saas',

  // Vendor gold rush
  'ven-pitches>ven-fomo',
  'ven-pitches>ven-free-pilots',
  'ven-pitches>dist-procurement',
  'ven-ai-washing>ven-pitches',
  'ven-ai-washing>cit-vetting|d',
  'ven-free-pilots>ven-procurement-bypass',
  'ven-fomo>ven-procurement-bypass',
  'ven-fomo>ven-license-duplication',
  'ven-procurement-bypass>shd-dept-saas',
  'ven-procurement-bypass>ven-lock-in',
  'ven-contract-backlog>ven-procurement-bypass',
  'ven-license-duplication>citi-funding',
  'ven-license-duplication>ven-renewal-squeeze',
  'ven-lock-in>ven-renewal-squeeze',
  'ven-renewal-squeeze>citi-funding',
  'aca-lms>ven-lock-in',

  // Teaching, research & services
  'aca-lms>pop-perceived-usefulness',
  'aca-lms>aca-teaching-quality',
  'aca-grants>aca-research-computing',
  'aca-research-computing>aca-research-advantage',
  'aca-research-advantage>aca-grants',
  'aca-assessment>aca-teaching-quality|d',
  'aca-assessment>pop-integrity-anxiety',
  'aca-course-policies>pop-fairness',
  'aca-course-policies>pop-integrity-anxiety',
  'aca-student-services>pop-visible-wins',
  'aca-data-readiness>aca-lms',
  'aca-data-readiness>aca-student-services',
  'aca-sanctioned-convenience>shd-adoption',
  'aca-curriculum>pop-student-fluency|d',
  'aca-curriculum>aca-teaching-quality',
];

// ── Featured feedback loops (Act 3 guided tours) ─────────────────────────────
export const loops = [
  {
    id: 'shadow-spiral', title: 'The Shadow Spiral', kind: 'reinforcing',
    nodes: ['cit-vetting', 'cit-catalog', 'pop-perceived-usefulness', 'shd-adoption', 'shd-data-leakage', 'cit-incident', 'cit-blocking', 'cit-vetting'],
    story: 'Vetting slows → the sanctioned catalog lags → sanctioned tools feel useless → people go shadow → data leaks → incidents pile up → IT responds by blocking → blocking consumes the capacity that was supposed to speed up vetting. Each turn of the wheel makes the next turn faster. This is the engine at the center of the map.',
  },
  {
    id: 'policy-lag', title: 'The Policy Lag Loop', kind: 'reinforcing',
    nodes: ['gov-policy-lag', 'gov-aup', 'gov-enforcement', 'pop-fairness', 'shd-adoption', 'gov-policy-lag'],
    story: 'Technology outruns policy → the acceptable-use policy describes last year’s tools → enforcement becomes inconsistent, because the rules don’t fit reality → inconsistency reads as unfairness → unfairness drives shadow adoption → shadow adoption widens the gap the policy has to cover. The delay marks (‖) on these edges are doing the damage.',
  },
  {
    id: 'talent-drain', title: 'The Talent Drain', kind: 'reinforcing',
    nodes: ['citi-staffing', 'citi-skills', 'cit-vetting', 'cit-catalog', 'pop-perceived-usefulness', 'shd-adoption', 'shd-data-leakage', 'cit-incident', 'citi-burnout', 'citi-staffing'],
    story: 'Industry pays double for AI skills → staff leave → skill and capacity fall → vetting and the catalog degrade → sanctioned tools disappoint → shadow use grows → incidents multiply → the remaining staff burn out cleaning them up → more staff leave. The original diagram had this exact loop about ANSF retention.',
  },
  {
    id: 'vendor-squeeze', title: 'The Vendor Squeeze', kind: 'reinforcing',
    nodes: ['ven-fomo', 'ven-license-duplication', 'citi-funding', 'citi-architecture', 'cit-catalog', 'pop-perceived-usefulness', 'dist-procurement', 'ven-fomo'],
    story: 'FOMO buys tools unit by unit → the same license is purchased nine times → duplicated spend drains central funding → the shared platform starves → the central catalog stays weak → units conclude central IT can’t deliver → they buy their own → which is what FOMO wanted. The gold rush funds itself out of your budget.',
  },
  {
    id: 'trust-flywheel', title: 'The Trust Flywheel', kind: 'balancing',
    nodes: ['pop-visible-wins', 'pop-trust-central', 'pop-disclosure', 'cit-visibility', 'cit-catalog', 'pop-perceived-usefulness', 'pop-visible-wins'],
    story: 'The one loop on the map that runs in the institution’s favor — if you can start it. Visible wins build trust → trust makes disclosure safe → disclosure gives IT real visibility → visibility improves the catalog → a better catalog is genuinely useful → usefulness produces more visible wins. Every phase-two conversation starts here.',
  },
];

// ── Act 2 scroll steps ────────────────────────────────────────────────────────
export const steps = [
  {
    id: 'terrain', cats: ['env'],
    kicker: 'IN THE ORIGINAL: PHYSICAL ENVIRONMENT',
    title: 'Start with the terrain',
    body: 'Afghanistan’s planners began with mountains and borders — the things no strategy could change. Our terrain is the technology itself: model capability doubling on a cadence of months, consumer AI in every pocket, costs nobody can forecast. No committee votes on the terrain. Everything else on this map is built on top of it.',
  },
  {
    id: 'population', cats: ['pop'],
    kicker: 'IN THE ORIGINAL: POPULATION CONDITIONS & BELIEFS',
    title: 'The center of gravity is people',
    body: 'The original’s planners put popular support at the center — five boxes running from "actively supporting the government" to "actively supporting the insurgency." Replace that with your faculty, students, and staff: from champions on the sanctioned path to people whose entire workflow left the institution months ago. Counterinsurgency doctrine and IT strategy agree on exactly one thing: you win or lose here, not at the firewall.',
  },
  {
    id: 'economy', cats: ['aca'],
    kicker: 'IN THE ORIGINAL: INFRASTRUCTURE, ECONOMY & SERVICES',
    title: 'What the struggle is actually over',
    body: 'In the original, this was roads, crops, and services — the real economy that determined whether the population could live a legitimate life. Ours is teaching, research, and student services: the actual work of the university. Note the node the original called "legit vs. illicit relative economic opportunity." Ours is "sanctioned vs. shadow relative convenience." People take the path that pays.',
  },
  {
    id: 'security', cats: ['cit'],
    kicker: 'IN THE ORIGINAL: AFGHANISTAN SECURITY FORCES',
    title: 'The forces asked to hold the line',
    body: 'The ANSF cluster tracked recruiting, training, morale, funding — an institution asked to secure territory while being built. Central IT holds the same position: asked to vet, secure, and provision AI for an entire university while competing with industry salaries for the very people who could do it. "Clear" operations (blocking) are easy. "Hold" operations (a sanctioned catalog people actually want) are the hard part — and the part that decides everything.',
  },
  {
    id: 'government', cats: ['gov'],
    kicker: 'IN THE ORIGINAL: GOVERNMENT',
    title: 'Policy, legitimacy, and the lag',
    body: 'The original tracked government capacity, rule of law, and perceived fairness. Ours: policy capacity, the acceptable-use policy, enforcement consistency — and the signature pathology, policy lag. Only 39% of institutions have an AI acceptable-use policy at all; the rest are governing a 2026 technology with a 2019 document. Every hash mark (‖) on these edges is a delay measured in semesters.',
  },
  {
    id: 'tribal', cats: ['dist'],
    kicker: 'IN THE ORIGINAL: TRIBAL GOVERNANCE',
    title: 'The layer the plan forgot',
    body: 'The original’s quietest, most important region: local structures with their own legitimacy, their own norms, and more real authority on the ground than the central government. That is distributed IT — college and departmental IT staff who are closest to the work and trusted by their people. Central strategy that integrates them gains a sensor network and an ally. Central strategy that bypasses them discovers, like every occupying force in history, that local governance does not simply vacate.',
  },
  {
    id: 'insurgency', cats: ['shd'],
    kicker: 'IN THE ORIGINAL: INSURGENTS',
    title: 'The insurgency is your own people',
    body: 'Here is where the analogy earns its keep — and where it gets uncomfortable. Roughly 56% of higher-ed workers use AI tools their institution doesn’t provide. The "insurgents" are your faculty and staff, doing institutional work with better tools than you gave them, supplied by the most capitalized industry on earth. They have safe havens (personal devices), coordination networks (group chats), superior agility (no procurement), and a recruiting pitch that writes itself: it just works.',
  },
  {
    id: 'narcotics', cats: ['ven'],
    kicker: 'IN THE ORIGINAL: CRIME & NARCOTICS',
    title: 'The economy that feeds on the chaos',
    body: 'The original mapped how the narcotics economy funded the insurgency and corroded every institution it touched. Our version is the edtech gold rush: free pilots that seed dependence, AI-washing that clogs every review queue, FOMO purchasing that fragments budgets, renewal pricing that harvests lock-in. None of it is illegal. All of it follows the same dynamics — an outside economy that profits from institutional weakness and reinvests in it.',
  },
  {
    id: 'coalition', cats: ['init'],
    kicker: 'IN THE ORIGINAL: COALITION FORCES & ACTIONS',
    title: 'The coalition, with the best intentions',
    body: 'The coalition had resources, resolve, and strategy documents — and limited understanding of the terrain, rotating leadership, and a domestic audience checking the results quarterly. Sound familiar? Task forces, flagship pilots, consultant frameworks, board pressure, leadership churn. The original’s most underrated node was "Coalition knowledge & understanding of social structures." Ours is leadership understanding of how departments actually work. Strategy written without it gets the reception occupying forces always get.',
  },
  {
    id: 'behold', cats: [],
    kicker: 'ALL EIGHT SYSTEMS, CONNECTED',
    title: 'When we understand this slide',
    body: 'Nine clusters. Over a hundred variables. More than two hundred causal links, some marked with the original’s "significant delay" hashes. This is not a parody of your institution — it is a reasonably careful model of it, exactly as the 2009 original was a reasonably careful model of Afghanistan. The slide was never the problem. The system was. Scroll on to explore every node — then let’s talk about what the map is actually for.',
  },
];

// ── Parse compact node/edge notation into objects ────────────────────────────
export const nodes = N.map(([id, cat, x, y, label, coin, desc, flags]) => ({
  id, cat, x, y, label, coin, desc, box: flags === 'b',
}));

export const edges = E.map((s) => {
  const delay = s.endsWith('|d');
  const [from, to] = (delay ? s.slice(0, -2) : s).split('>');
  return { from, to, delay };
});

export const nodeById = Object.fromEntries(nodes.map((n) => [n.id, n]));
export const catById = Object.fromEntries(categories.map((c) => [c.id, c]));

// Sanity: warn on dangling edge endpoints (dev aid; harmless in prod)
for (const e of edges) {
  if (!nodeById[e.from] || !nodeById[e.to]) {
    console.warn('[data] dangling edge', e.from, '>', e.to);
  }
}
for (const l of loops) {
  for (let i = 0; i < l.nodes.length - 1; i++) {
    const ok = edges.some((e) => e.from === l.nodes[i] && e.to === l.nodes[i + 1]);
    if (!ok) console.warn('[data] loop edge missing', l.id, l.nodes[i], '>', l.nodes[i + 1]);
  }
}
